### ISSUE TITLE
Groups: Discourse replies count not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#189]
On: https://mdmozdev.wpengine.com/groups/community-portal-qa/

The topic "This is a new topic" has one reply, it's not reflected on the reply count column.

![imagen](https://user-images.githubusercontent.com/531906/70816088-0ce52100-1dcf-11ea-996f-629cd3443916.png)

**Comment by dnaluz** [comment]
This looks like a bug with the Discourse API unless I am using the wrong field to get the reply count.   I am using this URL https://discourse-dev.itsre-apps.mozit.cloud/t/about-the-community-portal-qa-category/81.json to get the information on the category.  The reply count field for posts is 0.  Perhaps Leo could shed more light on this.

**Comment by dnaluz** [comment]
@nukeador I sent an email to Leo to see if he could shed some light on this issue, I've cc'd you  in the email.

**Comment by dnaluz** [comment]
Fixed!

**Comment by nukeador** [comment]
I still see 0 as reply count here

https://mdmozdev.wpengine.com/groups/community-portal-qa/

**Comment by dnaluz** [comment]
Hmmm, I'll have to speak with Leo on this one it should be using the update URL to pull topics the value coming back doesn't seem to match up.

**Comment by dnaluz** [comment]
Looks like the field reply_count isn't the field to get the replies to a topic.  I'll make the change and push it to the repo.  We won't be pushing any code updates this week so this won't be live until the new year!
